---
- hosts: webservers
  become: True
  tasks:
    - name: Add epel repository
      dnf:
         name: epel-release
         state: latest
      become: True
    - name: Ensure Jenkins repository is added
      yum_repository:
            name: jenkins-ci
            description: jenkins repository
            file: external_repos
            baseurl: http://pkg.jenkins-ci.org/redhat-stable
            gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
            gpgcheck: yes
    - name: Ensure gpg key is imported
      rpm_key:
              state: present
              key: https://pkg.jenkins.io/redhat/jenkins.io.key
    - name: Ensure Jenkins,python and java-devel packages installed
      yum:
              name: '{{ packages }}'
              state: present
              update_cache: true
      vars:
              packages:
                      - jenkins
                      - java-devel
                      - python3
    - name: Ensure systemd daemon-reload
      command: systemctl daemon-reload
    - name: Ensure Jenkins service is enabled and started
      service:
              name: jenkins
              state: started
